SELECT
    A.AUTHOR_ID,
    AUTHOR_NAME,
    CATEGORY,
    SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK B
JOIN AUTHOR A
    ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES S
    ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY B.AUTHOR_ID, CATEGORY
ORDER BY B.AUTHOR_ID, CATEGORY DESC