SELECT 
    USER_ID, 
    NICKNAME, 
    SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD
JOIN
    USED_GOODS_USER
ON WRITER_ID = USER_ID AND STATUS='DONE'
GROUP BY USER_ID
HAVING SUM(PRICE) >= 700000
ORDER BY TOTAL_SALES