SELECT
    INFO.INGREDIENT_TYPE,
    SUM(HALF.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO AS INFO
JOIN FIRST_HALF AS HALF
    ON INFO.FLAVOR = HALF.FLAVOR
GROUP BY INFO.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER
